### ISSUE TITLE
Place for general discussion?

### ISSUE THREAD

**Issue by f0k** [keunwoochoi/torchaudio-contrib#18]
Great you went public, I'm happy to see things moving forward!

The README file currently does not mention in what form discussions of the API and code should take place -- should this all happen in github issues, or do you have another means for more short-term communication?

To make this an issue and not just a question: The README file should be updated with a section on "Contributing".

**Comment by faroit** [comment]
> The README file currently does not mention in what form discussions of the API and code should take place -- should this all happen in github issues, or do you have another means for more short-term communication?

We don't really know ;-) The thing is that we want to come up with a proposal that we then want to formulate as code and then, hopefully, results in a PR for torchaudio. So in the end, we need to also discuss with @soumith and @dhpollack, that is why we might use the slack channel for communication and the issue for concrete proposals. What would you suggest?

**Comment by f0k** [comment]
> that is why we might use the slack channel for communication and the issue for concrete proposals

Yes, sounds good. Issues have the advantage of discussing in the open, but they are a larger hurdle than a chat message on slack. I just started two issues before I read your reply. Let's try to discuss those on github and if it doesn't play well, move the discussion to slack.

But feel free to add a "Contributing" paragraph stating something like "This is an early draft for a possible replacement of pytorch/audio. At this stage, discussion primarily takes place in the pytorch #audio slack channel; please request an invitation at https://github.com/pytorch/audio/issues/88 if you want to join."

**Comment by keunwoochoi** [comment]
Thanks :) 
+1 for github (Issues), especially over slack, which I'm afraid is not 100$ inclusive. As I just said in #16, we should make it explicit in README. You're experienced enough to have a couple of suggestions quickly, but I'd rather feel like to encourage people to share opinions here more than other repo's because that's what this repo is for.

**Comment by keunwoochoi** [comment]
For a new functionality, how about having a sort of structured procedure like

0. SEARCH if it was discussed before
1. Asking if some new thing can be useful to have (this part is quite often omitted in general, and I feel like.. how would you even finish implementing something even without being sure that it's gonna be used?)
2. (Optionally,) share a gist to discuss how it should be implemented
3. PR - review - merged.

..which is simple and nothing new, but making it explicit could be more encouraging and making things clearer.
