### ISSUE TITLE
Libtorch support?

### ISSUE THREAD

**Issue by dhpollack** [keunwoochoi/torchaudio-contrib#23]
Any thoughts on converting the functional parts of this to the c api and then calling those functions from python so people using libtorch could also use this library?  I feel like it would be useful for the small subset of users that don't want to rely on python and wouldn't be very difficult to implement.

**Comment by keunwoochoi** [comment]
I haven't thought about it yet but sounds good.

**Comment by keunwoochoi** [comment]
Hm, until there's someone volunteering I'll keep it closed.
