### ISSUE TITLE
HTK and Slaney

### ISSUE THREAD

**Issue by VinodS7** [keunwoochoi/torchaudio-contrib#24]
For reproducibility it would be useful to have these two mel filters. These are the two types of filters I have seen the most so correct me if there are other more important types of mel filters.

**Comment by keunwoochoi** [comment]
Agreed. Implementation wouldn't be a big issue, so would be the API design. PR would be welcome!

**Comment by VinodS7** [comment]
Will work on it. I am going to reimplement how librosa generates the filters in their backend. However, it is done in python and not in C. Also, I will write some tests that compare my implementation to librosa's but do we have a system in place for writing and evaluating tests?

**Comment by hagenw** [comment]
If you want to use the same test framework as PyTorch, [uinittest](https://docs.python.org/3/library/unittest.html) would be the way to go.
I would personally prefer [pytest](https://pytest.readthedocs.io/) which is great for doing parametrized tests, see also https://github.com/pytorch/pytorch/issues/11578.

To compare the actual outcome of the two implementation, something like `numpy.array_equal` or `numpy.testing.assert_almost_equal` might be of interest.

**Comment by keunwoochoi** [comment]
@VinodS7 Welcome and thanks :) 
> in python and not in C.

Would it make a big difference in computation time?

**Comment by keunwoochoi** [comment]
@hagenw Thanks for letting us know. Probably we should start with `unittest` and see how it goes there. @faroit @f0k Any thought?

**Comment by f0k** [comment]
> Probably we should start with unittest and see how it goes there. @faroit @f0k Any thought?

If there is no policy forbidding us to do so, I'd also prefer pytest.

> These are the two types of filters I have seen the most so correct me if there are other more important types of mel filters.

I think we should make it easy to reproduce most research papers, so (a) we should include these two filterbanks by default and (b) the API should make it easy to add your own.

**Comment by keunwoochoi** [comment]
Ok let's go with pytest.

**Comment by keunwoochoi** [comment]
@VinodS7 Hi, we'd love to hear from you if there's been any progress! :)

**Comment by ksanjeevan** [comment]
Should be easy to add Slaney following librosa https://librosa.github.io/librosa/_modules/librosa/core/time_frequency.html#hz_to_mel? Would just have to add them as options to [`MelFilterbank`](https://github.com/keunwoochoi/torchaudio-contrib/blob/af20c5bd60badcb8ab82ee83d1eb746c8e43a0e5/torchaudio_contrib/layers.py#L159)!

**Comment by VinodS7** [comment]
@keunwoochoi Hey. Sorry got caught up is some paper deadlines. I'll have it done by end of next week!

**Comment by keunwoochoi** [comment]
@VinodS7 Perfect, no problem, no rush. @ksanjeevan is working on Melspectrogram and I'm expecting to merge some update on it soon. It'll become obvious on which part of the code you should be work on. Thanks! :D
