### ISSUE TITLE
Python version

### ISSUE THREAD

**Issue by keunwoochoi** [keunwoochoi/torchaudio-contrib#41]
We never specified a version. After https://github.com/pytorch/audio/pull/100/commits, pytorch/audio implicitly became `py 3.5`-first. The main issues would be..

- Should we include `2.7`?
- What would be the `x`'s for `3.x`?

**Comment by faroit** [comment]
3.5-3.8 please ;-)

**Comment by hagenw** [comment]
I would also opt for 3.5- and not 2.7. But be aware that PyTorch has support for 2.7.

In https://github.com/pytorch/audio/pull/100 I included only Python 3.5 as [pytorch/audio](https://github.com/pytorch/audio) needs currently libpython-dev, which is not available for all Python versions on all Ubuntu versions.

I think it will be easier to solve, when the general installation procedure of [pytorch/audio](https://github.com/pytorch/audio) improves.

**Comment by keunwoochoi** [comment]
Yeah, I tentatively added `3.5` in the travis setting. 

https://github.com/keunwoochoi/torchaudio-contrib/commit/e642195bbf0e222d5e2ca5ff1a4dc7c095158125

**Comment by keunwoochoi** [comment]
Ok, let's not bother with <3.5 until we have any issue.
