### ISSUE TITLE
Displaying Spectrograms

### ISSUE THREAD

**Issue by kamalesh0406** [keunwoochoi/torchaudio-contrib#70]
Can we create a function to display Spectrograms similar to librosa.display.specshow . It would be better if all the functionality was within one library.

**Comment by keunwoochoi** [comment]
Hi, that's a nice idea but I'm afraid there are more 'core' stuff that lacks in torch/audio. By the way, some of the manifesto we claimed is now part of the official torch/audio (it should've been on the current readme) and I guess we can maybe archive this repo. I'll close it mainly for that reason :)
